version: "3.8"

services:
  php:
    build: ./php
    volumes:
      - ./php/uploads:/var/www/html
      - ./php/src/Dirty.php:/var/www/html/Dirty.php:ro
    networks:
      - ctfnet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - ctfnet

networks:
  ctfnet:
    driver: bridge
